version: "3.8"

services:
  web:
    build: .
    container_name: nextjs-static
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - cloudflare_nw
networks:
  cloudflare_nw:
    external: true